# Generated by Django 2.1.7 on 2019-03-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20190228_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='userprofile',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='userprofile',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
