# Generated by Django 2.1.7 on 2019-03-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20190302_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='information',
            field=models.TextField(default='fa efa'),
            preserve_default=False,
        ),
    ]
