# Generated by Django 2.1.7 on 2019-03-11 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20190304_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('total_attendance', models.IntegerField()),
                ('obtained_attendance', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lms.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'subject')},
        ),
    ]
